name: CI Pipeline

on:
  push:
    branches:
      - 4
    paths:
      - 'app/**'
      - 'tests/**'
      - 'routes/**'
      - 'database/**'
      - 'composer.json'
      - 'composer.lock'
      - 'Dockerfile'
      - 'docker-compose.yml'
  pull_request:
    branches:
      - 4
    paths:
      - 'app/**'
      - 'tests/**'
      - 'routes/**'
      - 'database/**'
      - 'composer.json'
      - 'composer.lock'
      - 'Dockerfile'
      - 'docker-compose.yml'
  workflow_dispatch:

jobs:
  ci:
    runs-on: self-hosted

    steps:
      # Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up PHP
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: pdo_mysql, gd, zip
          tools: composer

      # Install dependencies
      - name: Install dependencies
        run: make install

      # Run linting
    #   - name: Run linting
    #     run: make lint

      # Run tests
      - name: Run tests
        run: make test

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Build and push Docker image
      - name: Build and push Docker image
        run: |
          make docker-build
          make docker-push